import json
from urllib.parse import urlparse


def generate_postman_collection(
    parsed_data: dict,
    api_name: str = "API"
) -> dict:
    """
    Generates a Postman Collection v2.1 JSON from extracted endpoints.

    Args:
        parsed_data: Output from parser.parse_endpoints()
        api_name: Name of the API

    Returns:
        Postman collection as a Python dict (serialize with json.dumps)
    """
    base_url = parsed_data.get("base_url", "https://api.example.com")
    auth_method = parsed_data.get("auth_method", "API Key in Header")
    auth_header = parsed_data.get("auth_header", "Authorization: Bearer {{api_key}}")
    endpoints = parsed_data.get("endpoints", [])

    # Parse base URL
    parsed_base = urlparse(base_url)
    base_host = parsed_base.netloc or "api.example.com"
    base_path = parsed_base.path.strip("/")

    # Build auth header
    header_key = "Authorization"
    header_value = "Bearer {{api_key}}"
    if ":" in auth_header:
        parts = auth_header.split(":", 1)
        header_key = parts[0].strip()
        header_value = parts[1].strip()

    # Build collection items
    items = []
    for ep in endpoints:
        method = ep.get("method", "GET").upper()
        path = ep.get("path", "/").strip("/")
        description = ep.get("description", "")
        parameters = ep.get("parameters", [])

        # Build full URL
        full_path = f"{base_path}/{path}".strip("/") if base_path else path
        path_segments = [s for s in full_path.split("/") if s]

        # Build request body for POST/PUT/PATCH
        body = None
        if method in ["POST", "PUT", "PATCH"] and parameters:
            required_params = [
                p for p in parameters
                if p.get("required", False)
            ]
            if required_params:
                body = {
                    "mode": "urlencoded",
                    "urlencoded": [
                        {
                            "key": p.get("name", "param"),
                            "value": f"{{{{ {p.get('name','param')} }}}}",
                            "description": p.get("description", ""),
                            "type": "text"
                        }
                        for p in required_params
                    ]
                }

        # Build query params for GET
        query_params = []
        if method == "GET" and parameters:
            query_params = [
                {
                    "key": p.get("name", "param"),
                    "value": "",
                    "description": p.get("description", "")
                }
                for p in parameters
                if not p.get("required", True)
            ]

        item = {
            "name": description or f"{method} {path}",
            "request": {
                "method": method,
                "header": [
                    {
                        "key": header_key,
                        "value": header_value,
                        "type": "text"
                    },
                    {
                        "key": "Content-Type",
                        "value": "application/json",
                        "type": "text"
                    }
                ],
                "url": {
                    "raw": f"{base_url}/{path}",
                    "protocol": parsed_base.scheme or "https",
                    "host": base_host.split("."),
                    "path": path_segments,
                    "query": query_params
                },
                "description": description
            }
        }

        if body:
            item["request"]["body"] = body

        items.append(item)

    # Build full collection
    collection = {
        "info": {
            "name": f"{api_name} API Collection",
            "description": f"Auto-generated by Docsmith for {api_name} API",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "auth": {
            "type": "apikey",
            "apikey": [
                {"key": "key", "value": header_key, "type": "string"},
                {"key": "value", "value": "{{api_key}}", "type": "string"},
                {"key": "in", "value": "header", "type": "string"}
            ]
        },
        "variable": [
            {
                "key": "api_key",
                "value": "YOUR_API_KEY_HERE",
                "type": "string"
            },
            {
                "key": "base_url",
                "value": base_url,
                "type": "string"
            }
        ],
        "item": items
    }

    print(f"[postman] Collection generated — {len(items)} endpoints")
    return collection


def collection_to_json(collection: dict) -> str:
    """Returns the collection as a formatted JSON string."""
    return json.dumps(collection, indent=2)